100 Repetitions
Population: 100,000
Sensitivity: = 0.85
Specificity = 0.99
Stop Rule = 3
Sequential Testing = 3 times


Accuracy
Sensitivity
Specificity
number of batch testings
number of total testings

In [1]:
import Nehemiah_Batch_Testing as BTK #BTK is batch testing kit
import numpy as np

In [2]:
Constants = BTK.setupConstants(typeIIError = 0.15, typeIError = 0.01, batchLimit = 32)
Constants.typeIError

0.01

In [3]:
print(BTK.optimalBatchSize(0.01, Constants))
temp_list = []
subject_array = BTK.setupPopulation(populationSize=100, p=0.1)
batch_size = 10
temp = {'data': subject_array,
        'NB_Num': 0,
        'PB_Num': 0,
        'p': 0.1,
        'batch_size': batch_size}
temp_list.append(temp)
print(temp_list)


12
[{'data': array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  1],
       [ 6,  0],
       [ 7,  1],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [13,  1],
       [14,  0],
       [15,  0],
       [16,  0],
       [17,  1],
       [18,  0],
       [19,  1],
       [20,  0],
       [21,  1],
       [22,  0],
       [23,  0],
       [24,  1],
       [25,  0],
       [26,  0],
       [27,  1],
       [28,  0],
       [29,  0],
       [30,  1],
       [31,  0],
       [32,  0],
       [33,  0],
       [34,  0],
       [35,  0],
       [36,  0],
       [37,  0],
       [38,  1],
       [39,  0],
       [40,  1],
       [41,  0],
       [42,  0],
       [43,  0],
       [44,  0],
       [45,  0],
       [46,  1],
       [47,  0],
       [48,  0],
       [49,  0],
       [50,  0],
       [51,  0],
       [52,  0],
       [53,  0],
       [54,  0],
       [55,  0],
       [56,  0],
       [57,  0],
 

In [4]:
BTK.infectionRateNegativeBatch(p = 0.01, batchSize=32,Constants=Constants)

0.001976327594960294

In [5]:
batchSize = BTK.optimalBatchSize(p = 0.01, Constants = Constants)

In [6]:
random_table = np.random.uniform(size = 100)
print(random_table)

[7.28084073e-01 6.81814003e-01 9.05892657e-01 5.15472738e-01
 2.88317432e-01 5.75406014e-01 8.36762958e-01 9.52378666e-01
 5.69732115e-01 7.45554533e-01 9.06621206e-01 2.50713432e-01
 9.23862961e-01 9.19936933e-01 1.83339215e-01 6.73469912e-01
 1.88613294e-01 1.87308569e-01 5.95060456e-01 2.13624765e-01
 9.47478014e-01 7.06272056e-02 7.21664960e-01 8.08501937e-01
 9.22985114e-01 1.28375894e-01 3.24575984e-01 6.10919977e-02
 4.38467978e-03 2.51643943e-01 2.85584502e-01 6.66624143e-01
 9.08707282e-01 3.27394791e-01 8.50557819e-02 3.68275348e-02
 3.05108223e-01 6.10244173e-01 9.04769176e-01 3.94798196e-01
 2.58368159e-01 1.38836947e-01 4.48534352e-01 2.33873587e-01
 8.19030351e-01 3.57053460e-01 4.94893776e-01 5.26221288e-01
 6.27562944e-01 1.92902174e-01 4.37511298e-01 5.62143730e-01
 9.54711974e-01 9.76123233e-01 4.31498989e-01 7.08541522e-01
 8.57495268e-01 8.34136832e-01 2.93997945e-01 6.06346599e-01
 6.07708368e-01 2.71349291e-01 8.86541857e-01 9.34489440e-01
 6.38322093e-02 3.029864

In [7]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [8]:
subject_array = BTK.setupPopulation(populationSize=100, p=0.1)
BTK.batchSplit(subject_array,10, Constants)

(array([[ 0,  0],
        [ 1,  0],
        [ 2,  0],
        [ 3,  0],
        [ 4,  0],
        [ 5,  0],
        [ 6,  0],
        [ 7,  0],
        [ 8,  0],
        [ 9,  0],
        [10,  0],
        [11,  0],
        [12,  0],
        [13,  0],
        [14,  0],
        [15,  0],
        [16,  0],
        [17,  0],
        [18,  0],
        [19,  0],
        [60,  0],
        [61,  0],
        [62,  0],
        [63,  0],
        [64,  0],
        [65,  0],
        [66,  0],
        [67,  0],
        [68,  0],
        [69,  0],
        [70,  0],
        [71,  0],
        [72,  0],
        [73,  0],
        [74,  0],
        [75,  0],
        [76,  0],
        [77,  1],
        [78,  0],
        [79,  0]], dtype=int64),
 array([[20,  0],
        [21,  0],
        [22,  0],
        [23,  0],
        [24,  0],
        [25,  0],
        [26,  0],
        [27,  0],
        [28,  1],
        [29,  0],
        [30,  0],
        [31,  0],
        [32,  0],
        [33,  0],
        [34, 

In [9]:
BTK.sequentialTesting(subject_array, 3, 0.1, batchSize, Constants)

[[ 0  0]
 [ 1  0]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 5  0]
 [12  0]
 [13  0]
 [14  0]
 [15  0]
 [16  0]
 [17  0]
 [18  0]
 [19  0]
 [20  0]
 [21  0]
 [22  0]
 [ 6  0]
 [ 7  0]
 [ 8  0]
 [ 9  0]
 [10  0]
 [11  0]
 [23  0]
 [24  0]
 [25  0]
 [26  0]
 [31  0]
 [32  0]
 [33  0]
 [34  0]
 [35  0]
 [36  0]
 [37  0]
 [38  0]
 [39  0]
 [40  0]
 [56  0]
 [57  0]
 [58  0]
 [63  0]
 [64  0]
 [65  0]
 [66  0]
 [67  0]
 [68  0]
 [69  0]
 [70  0]
 [71  0]
 [72  0]
 [73  0]
 [74  0]
 [83  0]
 [84  0]
 [85  0]
 [86  0]
 [87  0]
 [88  0]
 [89  0]
 [90  0]
 [91  0]
 [92  0]
 [93  0]
 [41  0]
 [42  0]
 [51  0]
 [52  0]
 [53  0]
 [54  0]
 [55  1]
 [94  0]
 [95  0]
 [96  0]
 [45  0]
 [46  0]
 [47  0]
 [62  0]
 [75  0]
 [76  0]]


c:\users\nehem\appdata\local\programs\python\python39\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
